name: Test

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Dependencies
        run: pnpm install
      - name: Prepare
        run: pnpm run -r lint
      - name: Lint
        run: pnpm run -r lint
      - name: Check
        run: pnpm run -r check
